### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by badincite** [IOT-DSA/dslink-dart-mongodb#7]
any update instructions for the link I see no option to add connection just a place to set the broker address and nothing I enter works.

**Comment by ilyatsarev** [comment]
@badincite what exactly you enter and where?

**Comment by badincite** [comment]
Under links mongodb configs I set the broker address to mongodb://databaseip/databasename nothing shows up

Log shows

```
[2019-05-10 07:00:47.908728] == Exited with status 255 ==
[2019-05-10 07:00:47.877477] Unhandled exception:
[2019-05-10 07:00:47.877477] Could not import "package:logging/logging.dart" from "file:///C:/DSA/dsa-server/dslinks/mongodb/bin/run_old.dart": Could not resolve a package location for base at file:///C:/DSA/dsa-server/dslinks/mongodb/bin/run.dart
[2019-05-10 07:00:47.877477] #0      _asyncLoadErrorCallback (dart:_builtin:169)
[2019-05-10 07:00:47.877477] #1      _asyncLoadError (dart:_builtin:597)
[2019-05-10 07:00:47.877477] #2      _loadPackage (dart:_builtin:638)
[2019-05-10 07:00:47.877477] #3      _loadPackage.<anonymous closure> (dart:_builtin:654)
[2019-05-10 07:00:47.877477] #4      _handlePackagesReply (dart:_builtin:495)
[2019-05-10 07:00:47.877477] #5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
[2019-05-10 07:00:47.908728] == Exited with status 255 ==
[2019-05-10 07:00:47.877477] Unhandled exception:
[2019-05-10 07:00:47.877477] Could not import "package:logging/logging.dart" from "file:///C:/DSA/dsa-server/dslinks/mongodb/bin/run_old.dart": Could not resolve a package location for base at file:///C:/DSA/dsa-server/dslinks/mongodb/bin/run.dart
[2019-05-10 07:00:47.877477] #0      _asyncLoadErrorCallback (dart:_builtin:169)
[2019-05-10 07:00:47.877477] #1      _asyncLoadError (dart:_builtin:597)
[2019-05-10 07:00:47.877477] #2      _loadPackage (dart:_builtin:638)
[2019-05-10 07:00:47.877477] #3      _loadPackage.<anonymous closure> (dart:_builtin:654)
[2019-05-10 07:00:47.877477] #4      _handlePackagesReply (dart:_builtin:495)
[2019-05-10 07:00:47.877477] #5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
[2019-05-10 07:00:47.908728] == Exited with status 255 ==
```

**Comment by ilyatsarev** [comment]
@badincite broker address is the address of the DSA broker. To add new MongoDB database, right click on the Mongo dslink under /downstream and select "Add Database":

<img width="439" alt="Screenshot 2019-05-16 16 26 34" src="https://user-images.githubusercontent.com/5702621/57893374-86943c80-77f7-11e9-8579-475efdbc8c7e.png">

**Comment by badincite** [comment]
Just got back into this I did get it connected however I would have expected my find query to ouput a table with the all queried documents values
![1](https://user-images.githubusercontent.com/7386290/60107568-20bf9c80-9735-11e9-93ee-9a2dcd3e9e9f.PNG)

![2](https://user-images.githubusercontent.com/7386290/60107061-3da7a000-9734-11e9-9ba0-d17524b7b9d5.PNG)

**Comment by butlermatt** [comment]
@badincite Note that the db.collection.find() method returns a cursor. See the documentation from 
https://docs.mongodb.com/manual/reference/method/db.collection.find/

The second screenshot you show, is the objects referenced by the cursor, eg:
db.collection.find({something:true}).toArray(); (converts the cursor to an array of documents)

https://docs.mongodb.com/manual/reference/method/js-cursor/

**Comment by mneal-oii** [comment]
@butlermatt - it looks like putting ".toArray()" at the end of my query causes the link to disconnect. I am sure I am missing something but the goal is to access the data in my dataflow. Can you offer some direction here?
