### ISSUE TITLE
callback error in logs after trying to return a cursor.toArray()

### ISSUE THREAD

**Issue by roeviolator** [IOT-DSA/dslink-dart-mongodb#8]
Trying to return from a script block.  
Error I'm getting in mongo.log on my efm node:

```
[2019-12-01 17:07:24.235056] callback error; Exception: Failed to pack value: ObjectId("5de3eb7deccfa2e20f62aa25")
[2019-12-01 17:07:24.235069] #0      StatefulPacker.pack (package:msgpack/src/packer.dart:240:7)
[2019-12-01 17:07:24.235072] #1      StatefulPacker.packList (package:msgpack/src/packer.dart:376:7)
[2019-12-01 17:07:24.235074] #2      StatefulPacker.pack (package:msgpack/src/packer.dart:228:7)
[2019-12-01 17:07:24.235076] #3      StatefulPacker.packList (package:msgpack/src/packer.dart:376:7)
[2019-12-01 17:07:24.235079] #4      StatefulPacker.pack (package:msgpack/src/packer.dart:228:7)
[2019-12-01 17:07:24.235080] #5      StatefulPacker.packMap (package:msgpack/src/packer.dart:393:7)
[2019-12-01 17:07:24.235082] #6      StatefulPacker.pack (package:msgpack/src/packer.dart:230:7)
[2019-12-01 17:07:24.235084] #7      StatefulPacker.packList (package:msgpack/src/packer.dart:376:7)
[2019-12-01 17:07:24.235087] #8      StatefulPacker.pack (package:msgpack/src/packer.dart:228:7)
[2019-12-01 17:07:24.235089] #9      StatefulPacker.packMap (package:msgpack/src/packer.dart:393:7)
[2019-12-01 17:07:24.235090] #10     StatefulPacker.pack (package:msgpack/src/packer.dart:230:7)
[2019-12-01 17:07:24.235092] #11     pack (package:msgpack/src/packer.dart:7:19)
[2019-12-01 17:07:24.235094] #12     DsMsgPackCodecImpl.encodeFrame (package:dslink/src/utils/codec.dart:188:12)
[2019-12-01 17:07:24.235097] #13     WebSocketConnection.addData (package:dslink/src/http/websocket_conn.dart:325:28)
[2019-12-01 17:07:24.235098] #14     WebSocketConnection._send (package:dslink/src/http/websocket_conn.dart:315:7)
[2019-12-01 17:07:24.235100] #15     DsTimer._dsLoop (package:dslink/src/utils/timer.dart:212:10)
[2019-12-01 17:07:24.235103] #16     _rootRun (dart:async/zone.dart:1146)
[2019-12-01 17:07:24.235104] #17     _CustomZone.run (dart:async/zone.dart:1026)
[2019-12-01 17:07:24.235106] #18     _CustomZone.runGuarded (dart:async/zone.dart:924)
[2019-12-01 17:07:24.235108] #19     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
[2019-12-01 17:07:24.235110] #20     _rootRun (dart:async/zone.dart:1150)
[2019-12-01 17:07:24.235112] #21     _CustomZone.run (dart:async/zone.dart:1026)
[2019-12-01 17:07:24.235113] #22     _CustomZone.runGuarded (dart:async/zone.dart:924)
[2019-12-01 17:07:24.235115] #23     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
[2019-12-01 17:07:24.235117] #24     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
[2019-12-01 17:07:24.235119] #25     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
[2019-12-01 17:07:24.235121] #26     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
[2019-12-01 17:07:24.235122] #27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
[2019-12-01 17:07:24.235125]
[2019-12-01 17:07:24.236095] [INFO][DSA] Disconnected
[2019-12-01 17:07:24.237985] [INFO][DSA] Connected
```

Evaluate javascript block code:
```javascript
var mycursor = db.getCollection("test1:sprayChill1").find(
    {timestamp:
        {$gte: new ISODate("2019-12-01T16:34:04.257Z"), 
         $lte: new ISODate("2019-12-01T16:34:14.264Z")}});
return mycursor.toArray();
```

Alternate script works find - for example if I run the following, I do see the output printed in my mongodb.log

```javascript
var mycursor = db.getCollection("test1:sprayChill1").find(
    {timestamp:
        {$gte: new ISODate("2019-12-01T16:34:04.257Z"),
         $lte: new ISODate("2019-12-01T16:34:14.264Z")}});
mycursor.forEach(function (mydoc) {for(k in mydoc) {print(mydoc[k])}});
```

**Comment by roeviolator** [comment]
Update - After doing some digging and some reading and learning - I discovered what $eval is doing.  So I was able to modify the script I was using in the script block a bit.  -- .toArray() doesn't seem to work, however I can get an array to return in the script block by iterating over the cursor, and and doing an
`
myarray.push(tojson(doc));
return myarray;
`
